name: Quick Check

# This workflow provides fast feedback on pull requests
# by running essential checks without the full matrix
on:
  pull_request:

jobs:
  quick-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache gödel
        uses: actions/cache@v4
        with:
          path: ~/.godel
          key: ${{ runner.os }}-godel-${{ hashFiles('godelw', 'godel/config/godel.yml') }}
          restore-keys: |
            ${{ runner.os }}-godel-

      - name: Build and test
        run: |
          ./godelw build
          ./godelw test
          ./godelw verify --skip-test

      - name: Check for changes
        run: |
          # Ensure that running the build/verify doesn't change any files
          if [ -n "$(git status --porcelain)" ]; then
            echo "Files were modified by build/verify:"
            git status --porcelain
            git diff
            exit 1
          fi
